version: "3.8"

services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=kala
      - POSTGRES_USER=kala
      - POSTGRES_PASSWORD=kala
  web:
    build:
      context: .
    entrypoint: /run-local.sh
    volumes:
      - ./django_kala:/code
    ports:
      - "8080:8000"
    depends_on:
      - db
    environment:
      - DEPLOYMENT_ENVIRONMENT=development
      - DATABASE_USER=kala
      - DATABASE_PASSWORD=kala
      - DATABASE_NAME=kala
      - DATABASE_HOST=db
