services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=kala
      - POSTGRES_USER=kala
      - POSTGRES_PASSWORD=kala
  web:
    build:
      context: .
    entrypoint: /run-local.sh
    volumes:
      - ./django_kala:/code
    ports:
      - "8080:8000"
    depends_on:
      - db
    environment:
      - DEPLOYMENT_ENVIRONMENT=development
      - DATABASE_USER=kala
      - DATABASE_PASSWORD=kala
      - DATABASE_NAME=kala
      - DATABASE_HOST=db
  minio:
    image: quay.io/minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data

  minio-bootstrap:
    image: quay.io/minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set kala http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb kala/kala-docs;
      exit 0;
      "

volumes:
  minio_data:
