# Generated by Django 2.0.8 on 2018-10-02 00:15
from django.db import migrations


def create_permission(Permission, content_type, name):
    Permission.objects.get_or_create(name='Can manage {0}'.format(name), content_type=content_type, codename='can_manage')
    Permission.objects.get_or_create(name='Can invite users to {0}'.format(name), content_type=content_type, codename='can_invite')
    Permission.objects.get_or_create(name='Can create {0}'.format(name), content_type=content_type, codename='can_create')


def create_permissions(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    Permission = apps.get_model("auth", "Permission")
    create_permission(Permission, ContentType.objects.get_or_create(app_label='documents', model='document')[0], 'documents')
    create_permission(Permission, ContentType.objects.get_or_create(app_label='projects', model='project')[0], 'projects')
    create_permission(Permission, ContentType.objects.get_or_create(app_label='organizations', model='organization')[0], 'organizations')


class Migration(migrations.Migration):

    dependencies = [
        ('kala_auth', '0002_auto_20180116_0036'),
    ]

    operations = [
        migrations.RunPython(create_permissions),
    ]
