# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-08 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kala_auth', '0003_permissions_object_pk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissions',
            name='object_pk',
        ),
        migrations.AddField(
            model_name='permissions',
            name='object_uuid',
            field=models.UUIDField(default='123e4567-e89b-12d3-a456-426655440000'),
            preserve_default=False,
        ),
    ]
