# Generated by Django 2.0.8 on 2018-10-09 02:52

import auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kala_auth', '0003_auto_20181002_0231'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', auth.models.KalaUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
