# Generated by Django 2.0.8 on 2018-11-21 03:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('removed', models.DateField(null=True)),
                ('mime', models.CharField(max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'ordering': ['-date', 'name'],
                'db_table': 'kala_documents',
            },
        ),
        migrations.CreateModel(
            name='DocumentPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=255, null=True, upload_to='')),
                ('url', models.URLField(max_length=3000)),
                ('size', models.IntegerField(default=0)),
                ('description', models.TextField(null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('changed', models.DateTimeField(default=django.utils.timezone.now)),
                ('mime', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.Document')),
            ],
            options={
                'get_latest_by': 'created',
                'ordering': ['name', 'created'],
                'db_table': 'kala_document_version',
            },
        ),
    ]
