# Generated by Django 2.0.8 on 2018-11-21 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_localflavor_us.models
import timezone_field.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_auto_20181002_0231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('address1', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=80, null=True)),
                ('zip', models.CharField(blank=True, max_length=25, null=True)),
                ('country', models.CharField(blank=True, default='US', max_length=80, null=True)),
                ('fax', django_localflavor_us.models.PhoneNumberField(blank=True, max_length=20, null=True)),
                ('phone', django_localflavor_us.models.PhoneNumberField(blank=True, max_length=20, null=True)),
                ('locale', models.CharField(blank=True, default='en', max_length=2, null=True)),
                ('removed', models.DateField(null=True)),
                ('timezone', timezone_field.fields.TimeZoneField(default='UTC')),
                ('website', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'kala_companies',
            },
        ),
        migrations.CreateModel(
            name='OrganizationPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Organization')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
