# -*- mode: ruby -*-
# vi: set ft=ruby :

PROJECT = "kala"
PROJECT_URL = "kala.example.com"

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"

  config.vm.network "forwarded_port", guest: 80, host: 9090

  config.vm.synced_folder "../", "/srv/" + PROJECT + "-app"

  config.vm.provider "virtualbox" do |vb|
    vb.name = PROJECT
    vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
    vb.memory = "1024"
  end

  config.vm.provision "shell", path: "provision/provision.sh", args: [PROJECT, PROJECT_URL]
end
