# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 20:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('removed', models.DateField(null=True)),
                ('changed', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('clients', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
            ],
            options={
                'db_table': 'kala_projects',
                'ordering': ('name',),
            },
        ),
    ]
