# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_export'),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='name',
            field=models.CharField(default='foo', max_length=255),
            preserve_default=False,
        ),
    ]
