# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-08 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


def add_uuid(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')
    for row in Project.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])

class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20171008_2046'),
    ]

    operations = [
        migrations.RunPython(add_uuid),
        migrations.AlterField(
            model_name='project',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
