# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "trusty64"
  config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"

  # Change the name from a random string to kala
  config.vm.provider "virtualbox" do |p|
      p.name = "kala"
  end
  config.vm.define :kala do |t|
  end

  # Forward port 80 => 9000 on the host, so you will see this at
  # http://localhost:9000
  config.vm.network "forwarded_port", guest: 80, host: 9000

  # Share the kala folder
  config.vm.synced_folder "../kala", "/srv/kala"

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "manifests"
    puppet.manifest_file  = "init.pp"
  end
end
