#!/bin/bash

# Update the system.
apt update
DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" upgrade

# This ubuntu box does not set the locale correctly, which was causing postgres
# to use LATIN1 as the encoding, not what we want. So manualy set things to UTF8
locale-gen en_US.UTF-8
cat > /etc/default/locale <<- EOM
#  File generated by update-locale
LC_ALL=en_US.UTF-8
LANG=en_US.UTF-8
EOM

sudo apt install postgresql-client libcurl4-openssl-dev uwsgi uwsgi-plugin-python3 nginx
